import MainMenu from '@/components/MainMenu'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import { auth } from '@/auth'
import LocaleSwitcher from '@/components/LanguageSelector/LocaleSwitcher'
import { routing } from '@/i18n/routing'
import { SessionProvider } from 'next-auth/react'
import { hasLocale, NextIntlClientProvider } from 'next-intl'
import { setRequestLocale } from 'next-intl/server'
import { notFound } from 'next/navigation'
import RoadmapCard from '../components/RoadmapCard'
import TagsCard from '../components/TagsCard'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale: string }>
}>) {
  const session = await auth()
  const { locale } = await params

  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  setRequestLocale(locale)

  return (
    <SessionProvider session={session}>
      <html lang={locale}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} h-screen bg-ghostWhite antialiased`}
          suppressHydrationWarning
        >
          <NextIntlClientProvider>
            <LocaleSwitcher />

            <MainMenu>
              <div className='flex flex-col gap-4 p-4'>
                <TagsCard />
                <RoadmapCard />
              </div>
            </MainMenu>
            {children}
          </NextIntlClientProvider>
        </body>
      </html>
    </SessionProvider>
  )
}
